#!/bin/bash
if [ "$1"x = "start"x ]||[ "$1"x = "stop"x ]||[ "$1"x = "restart"x ];then
    /usr/local/bin/brew services $1 $2
elif [ "$1"x = "status"x ];then
    /usr/local/bin/brew services list 
else
    /usr/local/bin/brew services $2 $1
fi
